# Generated by Django 2.0 on 2021-07-28 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tilte',
            new_name='title',
        ),
    ]
